title = "IVP config"

name = "BE"
t_f = 1
# Cant add more than 100 becuase solution explodes
#number_of_sites = [32, 48, 64, 80, 100, 120, 300]
#number_of_sites = [20, 32, 48, 64, 80 ]
number_of_sites = [ 120, 300, 500, 650]
#number_of_sites = [100]
#number_of_sites = [16, 32]
k_h_power = 2
ratio = 15