title = "IVP config"

name = "df"
#t_f = 1
t_f = 1
# Cant add more than 100 becuase solution explodes
#number_of_sites = [16, 32, 64, 100, 150,300]
number_of_sites = [10, 20, 30, 40, 50, 60]
k_h_power = 3
ratio = 0.5