title = "IVP config"

#t_f = 1
name="LF"
t_f = 1
# Cant add more than 100 becuase solution explodes
#number_of_sites = [39, 64, 80, 100, 150, 200]
number_of_sites = [151, 160, 180, 200]
#number_of_sites = [100]
k_h_power = 2
ratio = 0.24999
